---
name: Getopt-Lucid
version: 0.10
author:
  - David A Golden <dagolden@cpan.org>
abstract: Put abstract here
license: perl
requires:
  Exception::Class: 1.2
  perl: 5.006
build_requires:
  Exception::Class::TryCatch: 1.05
  Test::Deep: 0.087
  Test::Exception: 0.2
  Test::More: 0.47
provides:
  Getopt::Lucid:
    file: lib/Getopt/Lucid.pm
    version: 0.10
  Getopt::Lucid::Exceptions:
    file: lib/Getopt/Lucid/Exceptions.pm
    version: 0.10
generated_by: Module::Build version 0.2701
